# Generated by Django 2.1.4 on 2023-03-22 02:36

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_pic', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('username', models.TextField(blank=True, max_length=127, null=True)),
                ('apartment', models.TextField(blank=True, max_length=127, null=True)),
                ('area_name', models.TextField(blank=True, max_length=127, null=True)),
                ('house_no', models.TextField(blank=True, max_length=127, null=True)),
                ('county', models.CharField(blank=True, choices=[('Westlands', 'Westlands'), ('Langata', 'Langata'), ('Kibra', 'Kibra'), ('Embakasi North', 'Embakasi North'), ('Embakasi South', 'Embakasi South'), ('Embakasi Central', 'Embakasi Central'), ('Embakasi West', 'Embakasi West'), ('Embakasi East', 'Embakasi East'), ('Makadara', 'Makadara'), ('Starehe', 'Starehe')], default='Kenya', max_length=127, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('no_of_orders', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('text', models.TextField()),
                ('sent_date', models.DateField(auto_now_add=True, null=True)),
                ('to_address', models.CharField(max_length=255)),
                ('from_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'at_private_messages',
            },
        ),
    ]
